@Library("yorosis-shared-library") _

standardPipeline {
    projectType = "java-service"
    deploymentName = "authnz-service-deployment"
    dockerImageName = "authnz-service"
    canSkipSonarQubeCheck = true
    canBuildDockerImage = true
    canDeployImage = true
}
