apiVersion: apps/v1
kind: Deployment
metadata:
  name: authnz-service-deployment
spec: 
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: authnz-service
  template: 
    metadata:
      labels:
        app: authnz-service
        tier: backend
    spec:
      containers:
      - name: authnz-service
        image: yorosis/authnz-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits: 
            cpu: 1000m
            memory: 1Gi
          requests: 
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /authnz-service/health/v1/ping
            port: 8080
          initialDelaySeconds: 25
          timeoutSeconds: 1
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /authnz-service/health/v1/ping
            port: 8080
          initialDelaySeconds: 35
          timeoutSeconds: 1
          periodSeconds: 15
          failureThreshold: 3
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        - name: QUEUE_USER
          valueFrom:
            secretKeyRef:
              name: queue-secret
              key: username
        - name: QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: queue-secret
              key: password
        - name: QUEUE_SERVICE_NAME
          valueFrom:
            secretKeyRef:
              name: queue-secret
              key: service_name
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: salt-secret
              key: encryptor.password
          
        - name: CONNECTION_POOL_MIN_IDLE
          valueFrom:
            configMapKeyRef:
              name: yoroapps-config
              key: connection.pool.min.idle
        - name: CONNECTION_POOL_MAX_SIZE
          valueFrom:
            configMapKeyRef:
              name: yoroapps-config
              key: connection.pool.max.size

      imagePullSecrets:
      - name: hub-docker-secret