
CREATE SCHEMA yoroflow AUTHORIZATION "liveappsuser"

CREATE TABLE yoroflow.users (user_id uuid NOT NULL,	active_flag varchar(1) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,	email_id varchar(355) NOT NULL,	first_name varchar(100) NULL,last_login timestamp NULL,	last_name varchar(100) NULL,modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL,user_name varchar(200) NULL, user_password varchar(200) NULL,	user_type varchar(10) NULL,	profile_picture varchar NULL,contact_email_id varchar(355) NOT NULL,contact_mobile_number varchar(50) NULL, otp_provider varchar(20) NULL, otp_secret varchar(200) NULL, auth_type varchar(20) NULL, auth_token varchar(4000) NULL, auth_expiration_date timestamp NULL, is_two_factor varchar(1) NULL, PRIMARY KEY (user_id))
CREATE TABLE yoroflow."group" (group_id uuid NOT NULL,group_name varchar NOT NULL,group_desc varchar NULL,created_by varchar NULL,created_date timestamp NULL,updated_by varchar NULL,updated_date timestamp NULL,active_flag varchar NULL,	tenant_id varchar NULL,	PRIMARY KEY (group_id))
CREATE TABLE yoroflow.yoro_groups ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, description varchar(255) NOT NULL, group_name varchar(100) NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, managed_flag varchar(1) NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.yoro_groups_user ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NULL, created_on timestamp NULL, modified_by varchar(100) NULL, modified_on timestamp NULL, tenant_id varchar(60) NOT NULL, user_id uuid NOT NULL, group_id uuid NOT NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.grids ( grid_id uuid NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, default_no_of_rows int4 NOT NULL, default_sortable_column varchar(255) NULL, exportable varchar(5) NOT NULL, filterable varchar(5) NOT NULL, grid_name varchar(200) NULL, grid_url varchar(255) NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, module_name varchar(200) NULL, pass_params varchar(200) NULL, show_check_box varchar(255) NULL, tenant_id varchar(60) NOT NULL, where_clause varchar(500) NULL, width_percentage int4 NULL, sort_direction varchar(50) NULL, managed_flag varchar(1) NULL, field_values varchar(100) NULL,user_specific_grid_data varchar(1) NULL,grid_column_names varchar(100) NULL,PRIMARY KEY (grid_id) )
CREATE TABLE yoroflow.grid_columns ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, column_name varchar(50) NOT NULL, column_sequence_no int4 NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, display_name varchar(100) NOT NULL, field_type varchar(25) NOT NULL, filterable varchar(5) NOT NULL, hidden_value varchar(5) NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, object_field_name varchar(25) NULL, sortable varchar(5) NOT NULL, tenant_id varchar(60) NOT NULL, width_percentage int4 NULL, grid_id uuid NOT NULL, date_time_format varchar(50) NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.grid_filter ( filter_id uuid NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, filter_name varchar(100) NOT NULL, filter_type varchar(100) NOT NULL, filter_value varchar(100) NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, "operator" varchar(50) NOT NULL, tenant_id varchar(60) NOT NULL, grid_id uuid NOT NULL, PRIMARY KEY (filter_id) );
CREATE TABLE yoroflow.page ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, description varchar(255) NULL, layout_type varchar(50) NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, page_data json NOT NULL, page_id varchar(200) NOT NULL, page_link varchar(255) NULL, page_name varchar(200) NOT NULL, tenant_id varchar(60) NOT NULL, application_id uuid NOT NULL, qualifier varchar(255) NULL, status varchar(255) NULL, page_version int8 NULL, is_workflow_form varchar NULL, managed_flag varchar(1) NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.page_permissions ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, create_allowed varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, delete_allowed varchar(1) NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, read_allowed varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, update_allowed varchar(1) NOT NULL, page_id uuid NULL, group_id uuid NOT NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.table_objects ( table_objects_id uuid NOT NULL, table_name varchar(100) NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, tenant_id varchar(30) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, table_identifier varchar NULL, managed_flag varchar(10) NULL, public_table varchar(1) NULL,  PRIMARY KEY (table_objects_id) )
CREATE TABLE yoroflow.table_objects_columns ( id uuid NOT NULL, table_objects_id uuid NOT NULL, column_name varchar(100) NOT NULL, data_type varchar(100) NOT NULL, field_size int8 NULL, is_unique varchar(100) NOT NULL, is_required varchar(100) NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, tenant_id varchar(30) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, column_identifier varchar NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.menu ( menu_id uuid NOT NULL, active_flag varchar(1) NOT NULL, collapsible varchar(5) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, menu_name varchar(100) NOT NULL, menu_orientation varchar(50) NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, application_id uuid NULL, managed_flag varchar(1) NULL, PRIMARY KEY (menu_id) )
CREATE TABLE yoroflow.menu_details ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, menu_name varchar(100) NOT NULL, menu_path varchar(100) NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, page_id uuid NULL, tenant_id varchar(60) NOT NULL, menu_id uuid NOT NULL, parent_menu_id uuid NULL, display_order int8 NULL, custom_page_id uuid NULL, icon varchar(25) NULL, report_id uuid NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.application ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, app_name varchar(200) NOT NULL, app_prefix varchar(4) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, description varchar(200) NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, timezone varchar(100) NULL, default_language varchar(50) NOT NULL, application_id varchar(200) NOT NULL, left_menu_id uuid NULL, theme_id varchar(50) NULL, logo varchar NULL, right_menu_id uuid NULL, top_menu_id uuid NULL, bottom_menu_id uuid NULL, managed_flag varchar(1) NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.application_permissions ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, create_allowed varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, delete_allowed varchar(1) NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, read_allowed varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, update_allowed varchar(1) NOT NULL, application_id uuid NOT NULL, group_id uuid NOT NULL, launch_allowed varchar(1) NULL, edit_allowed varchar(1) NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.custom_pages ( id uuid NOT NULL, page_id varchar NOT NULL, "json" json NULL, application_id uuid NULL, tenant_id varchar NULL, page_name varchar NULL, menu_path varchar NULL, active_flag varchar(1) NULL, page_version int8 NULL, managed_flag varchar(1) NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.custom_page_permissions ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, create_allowed varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, delete_allowed varchar(1) NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, read_allowed varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, update_allowed varchar(1) NOT NULL, custom_page_id uuid NULL, group_id uuid NOT NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.yorosis_themes ( id uuid NOT NULL, theme_name varchar NULL, theme_id varchar NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, active_flag varchar(1) NOT NULL, tenant_id varchar(60) NULL, PRIMARY KEY (id) );
CREATE TABLE yoroflow.organization ( id uuid NOT NULL, active_flag varchar(1) NOT NULL, allowed_domain_names varchar(300) NULL,organization_url varchar(255) NULL,subdomain_name varchar(100) NOT NULL,created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, org_name varchar(200) NOT NULL, tenant_id varchar(60) NOT NULL, logo varchar NULL, theme_id varchar NULL, background_image varchar(255) NULL, enable_two_factor varchar(1) NULL, PRIMARY KEY (id) );


CREATE TABLE yoroflow.process_instance ( created_by varchar(100) NULL, created_date timestamp NULL, updated_by varchar(100) NULL, updated_date timestamp NULL, process_instance_id uuid NOT NULL, status varchar NULL, start_time timestamp NULL, end_time timestamp NULL, started_by varchar NULL, completed_by varchar NULL, start_task uuid NULL, end_task uuid NULL, process_definition_id uuid NULL, tenant_id varchar(60) NULL, initiated_by_task_id uuid NULL, PRIMARY KEY (process_instance_id) )
CREATE TABLE yoroflow.process_instance_task_file ( task_file_att_id uuid NOT NULL, process_instance_task_id uuid NOT NULL, file_name varchar(20) NULL, added_by uuid NOT NULL, created_date timestamp NOT NULL, updated_date timestamp NOT NULL, files bytea NULL, tenant_id varchar(60) NULL, created_by varchar(100) NULL, updated_by varchar(100) NULL, PRIMARY KEY (task_file_att_id) )
CREATE TABLE yoroflow.process_instance_task_notes ( task_notes_att_id uuid NOT NULL, process_instance_task_id uuid NOT NULL, notes varchar(300) NULL, added_by uuid NOT NULL, created_date timestamp NOT NULL, updated_date timestamp NOT NULL, updated_by varchar NOT NULL, tenant_id varchar(60) NULL, created_by varchar(100) NULL, PRIMARY KEY (task_notes_att_id) )
CREATE TABLE yoroflow.process_instance_tasks ( created_by varchar(100) NULL, created_date timestamp NULL, updated_by varchar(100) NULL, updated_date timestamp NULL, process_instance_id uuid NULL, process_instance_task_id uuid NOT NULL, assigned_to uuid NULL, start_time timestamp NULL, end_time timestamp NULL, task_id uuid NULL, status varchar NULL, description varchar NULL, due_date timestamp NULL, "data" json NULL, tenant_id varchar(60) NULL, due_date_event_processed_on timestamp NULL, assigned_to_group uuid NULL, referred_by uuid NULL, task_completion_remainder timestamp NULL, initiated_process_instance_alias varchar NULL, initiated_process_instance_id uuid NULL, reminder_task json NULL, task_data jsonb NULL, PRIMARY KEY (process_instance_task_id) )
CREATE TABLE yoroflow.process_definitions ( process_definition_id uuid NOT NULL, process_definition_name varchar(4000) NOT NULL, created_by varchar(100) NULL, created_date timestamp NULL, updated_by varchar(100) NULL, updated_date timestamp NULL, process_definition_key varchar NOT NULL, start_task_key varchar(50) NULL, workflow_structure varchar(50000) NULL, status varchar NULL, workflow_version int8 NULL, tenant_id varchar(60) NULL, user_name varchar(100) NULL, active_flag varchar(60) NULL, "key" varchar(250) NULL, scheduler_expression varchar NULL,  start_type varchar(100) NULL,upload_workflow varchar(60) NULL,approve varchar(1) NULL,install_workflow varchar(255) NULL, PRIMARY KEY (process_definition_id) )
CREATE TABLE yoroflow.process_definition_tasks ( process_definition_id uuid NOT NULL, task_id uuid NOT NULL, task_name varchar NULL, assigned_to varchar NULL, assigned_to_type varchar NULL, status varchar NULL, parent_step_key varchar(100) NULL, task_type varchar NULL, form_id varchar NULL, target_step_key varchar NULL, created_by varchar(100) NULL, created_date timestamp NULL, updated_by varchar(100) NULL, updated_date timestamp NULL, task_step_key varchar NOT NULL, tenant_id varchar(60) NULL, scheduler_expression varchar(300) NULL, PRIMARY KEY (task_id) )
CREATE TABLE yoroflow.process_definition_permission ( process_def_prmsn_id uuid NOT NULL, process_definition_id uuid NOT NULL, group_id uuid NOT NULL, update_allowed varchar NULL, read_allowed varchar NULL, launch_allowed varchar NULL, publish_allowed varchar(1) NOT NULL, created_by varchar NULL, created_date timestamp NULL, updated_by varchar NULL, updated_date timestamp NOT NULL, active_flag varchar(1) NULL, tenant_id varchar NULL, PRIMARY KEY (process_def_prmsn_id) )
CREATE TABLE yoroflow.process_def_task_properties ( task_id uuid NULL, task_properties_id uuid NOT NULL, property_name varchar(50) NULL, property_value json NULL, process_definition_id varchar(100) NULL, created_by varchar(100) NULL, created_date timestamp NULL, updated_by varchar(100) NULL, updated_date timestamp NULL, tenant_id varchar(60) NULL, PRIMARY KEY (task_properties_id) )
CREATE TABLE yoroflow.process_def_task_permission ( process_def_task_prms_id uuid NOT NULL, user_id uuid NULL, created_by varchar(100) NULL, created_date timestamp NULL, updated_by varchar(100) NULL, updated_date timestamp NULL, tenant_id varchar(60) NULL, task_id uuid NOT NULL, group_id uuid NULL, read_allowed varchar(1) NULL, update_allowed varchar NULL, execute_allowed varchar(1) NULL, PRIMARY KEY (process_def_task_prms_id) )
CREATE TABLE yoroflow.process_queue ( process_queue_id uuid NOT NULL, process_instance_id uuid NOT NULL, process_definition_task_id uuid NOT NULL, picked_up_by varchar NULL, picked_up_timestamp timestamp NULL, created_timestamp timestamp NOT NULL, status varchar(20) NOT NULL, error_description varchar(10000) NULL, PRIMARY KEY (process_queue_id) )
CREATE TABLE yoroflow.message_group ( id uuid NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, group_name varchar NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.message_group_users ( id uuid NOT NULL, message_group_id uuid NOT NULL, user_id uuid NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, PRIMARY KEY (id))
CREATE TABLE yoroflow.message_history ( id uuid NOT NULL, from_id uuid NOT NULL, to_id uuid NULL, message varchar NOT NULL, read_time timestamp NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, group_id uuid NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.notifications ( id uuid NOT NULL, from_id uuid NOT NULL, to_id uuid NULL, message varchar NOT NULL, read_time timestamp NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, task_id uuid NULL, group_id uuid NULL, "type" varchar(100) NULL, taskboard_id uuid NULL, taskboard_task_id uuid NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.group_message_read_times ( id uuid NOT NULL, message_history_id uuid NOT NULL, read_time timestamp NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, user_id uuid NOT NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.shedlock ( "name" varchar(64) NOT NULL, lock_until timestamp NULL, locked_at timestamp NULL, locked_by varchar(255) NULL, PRIMARY KEY (name) );
CREATE TABLE yoroflow.environment_variable ( id uuid NOT NULL, process_definition_id uuid NOT NULL, "name" varchar(250) NOT NULL, value varchar(250000) NOT NULL, tenant_id varchar(250) NOT NULL, active_flag varchar(250) NOT NULL, created_by varchar NULL, updated_by varchar NULL, created_date timestamp NULL, updated_date timestamp NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.service_token ( id uuid NOT NULL, api_name varchar(100) NOT NULL, api_key varchar(100) NOT NULL, secret_key varchar(100) NOT NULL, expires_on timestamp NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, user_id uuid NOT NULL, internal varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL,  PRIMARY KEY (id))
CREATE TABLE yoroflow.user_permission ( id uuid NOT NULL, page_id varchar(200) NULL, page_name varchar(200) NULL, workflow_key varchar(200) NULL, workflow_name varchar(200) NULL, active_flag varchar(1) NOT NULL, create_allowed varchar(1) NULL, delete_allowed varchar(1) NULL, read_allowed varchar(1) NULL, update_allowed varchar(1) NULL, launch_allowed varchar(1) NULL, publish_allowed varchar(1) NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, "version" int8 NULL, service_token_id uuid NOT NULL, PRIMARY KEY (id) )
CREATE TABLE yoroflow.user_custom_attribute (id uuid NOT NULL, attribute_name varchar(400) NOT NULL, attribute_value varchar(1000) NOT NULL, attribute_datatype varchar(60) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, active_flag varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, user_id uuid NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.org_custom_attributes (id uuid NOT NULL, attribute_name varchar(400) NOT NULL, attribute_value varchar(1000) NULL, attribute_datatype varchar(60) NOT NULL, attribute_type varchar(60) NOT NULL, attribute_size int8 NOT NULL, attribute_required varchar(60) NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, active_flag varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.email_template (id uuid NOT NULL, template_name varchar(100) NOT NULL, template_id varchar(100) NOT NULL, template_data varchar(100000) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, active_flag varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, managed_flag varchar(1) NULL, template_subject varchar(1000) null, PRIMARY KEY (id));
CREATE TABLE yoroflow.organization_preferences (id uuid NOT NULL, default_page_size int4 NOT NULL, pending_task_color varchar(100) NOT NULL, completed_task_color varchar(100) NOT NULL, error_task_color varchar(100) NOT NULL, draft_task_color varchar(100) NOT NULL, approve_task_color varchar(100) NOT NULL, reject_task_color varchar(100) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, active_flag varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.yoro_time_zone (id uuid NOT NULL, time_zone_code varchar(100) NOT NULL, time_zone_label varchar(100) NOT NULL, default_time_zone varchar(1) NOT NULL, created_by varchar(100) NULL, created_date timestamp NULL, updated_by varchar(100) NULL, updated_date timestamp NULL, tenant_id varchar(60) NOT NULL, active_flag varchar(1) NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.counter_values (counter_id uuid NOT NULL, process_definition_id uuid NULL, process_definition_key varchar(100) NOT NULL, counter_type varchar(10) NOT NULL, reset_at int8 NULL, counter_value int8 NULL, counter_name varchar(100) NOT NULL, count_increased_by int4 NOT NULL, counter_start_at int4 NOT NULL,time_zone varchar(60) NULL, counter_date date NULL, created_by varchar(100) NULL, created_date timestamp NULL, updated_by varchar(100) NULL, updated_date timestamp NULL, tenant_id varchar(60) NOT NULL, active_flag varchar(1) NOT NULL, PRIMARY KEY (counter_id));
CREATE TABLE yoroflow.metrics_data (id uuid NOT NULL, metric_type varchar(10) NOT NULL, task_id uuid NOT NULL, recipient_id varchar(50) NOT NULL, created_by varchar(50) NOT NULL, created_on timestamp NOT NULL, sent_timestamp timestamp NOT NULL, tenant_id varchar(50) NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.custom_menu_mobile (id uuid NOT NULL,active_flag varchar(1) NOT NULL,tenant_id varchar(60) NOT NULL,custom_menu_name varchar(100) NULL,custom_page_name varchar(100) NULL,default_menu_name varchar(100) NULL,created_by varchar(100) NOT NULL,modified_on timestamp NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.org_sms_settings (id uuid NOT NULL,active_flag varchar(1) NOT NULL,tenant_id varchar(60) NOT NULL,provider_name varchar(100) NULL,secret_key varchar(500) NULL,secret_token varchar(500) NULL,created_by varchar(100) NOT NULL,modified_on timestamp NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NOT NULL,from_phone_number varchar(20) NULL,service_name varchar(50) NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.users_workflow_pins (id uuid NOT NULL, user_id uuid NOT NULL, process_definition_key varchar(100) NOT NULL, tenant_id varchar NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, updated_date timestamp NOT NULL, created_date timestamp NOT NULL, updated_by varchar(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.process_instance_errors (id uuid NOT NULL, process_definition_id uuid NOT NULL, process_instance_id uuid NOT NULL, process_instance_task_id uuid NOT NULL, error_description varchar(2000) NOT NULL, resolution_status varchar(100) NULL, created_by varchar(50) NOT NULL, created_date timestamp NOT NULL, updated_by varchar(100) NULL, updated_date timestamp NULL, tenant_id varchar(50) NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.market_place_installed_apps (id uuid NOT NULL,active_flag varchar(1) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NOT NULL,modified_on timestamp NOT NULL,process_definition_name varchar(255) NULL,tenant_id varchar(60) NOT NULL,description varchar(250) NULL,start_key varchar(255) NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.shopping_cart ( id uuid NOT NULL, cart_name varchar(100) NOT NULL, cart_label varchar(100) NOT NULL, cart_data json NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, active_flag varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.workflow_report ( report_id uuid NOT NULL, report_name varchar(100) NOT NULL, report_type varchar(100) NOT NULL, workflow_name varchar(100) NOT NULL, workflow_key varchar(100) NOT NULL, workflow_version int4 NOT NULL, task_name varchar(100) NOT NULL, report_json json NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, active_flag varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, enable_report varchar(1) NULL, created_by varchar(255) NULL, task_id uuid NULL, PRIMARY KEY (report_id));
CREATE TABLE yoroflow.workflow_report_permission ( id uuid NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, active_flag varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, report_id uuid NOT NULL, group_id uuid NOT NULL, created_by varchar(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE yoroflow.user_otp_recovery_codes ( id uuid NOT NULL, user_id uuid NOT NULL, recovery_code varchar(60) NOT NULL,  created_on timestamp NOT NULL, created_by varchar(100) NOT NULL, active_flag varchar(1) NOT NULL, tenant_id varchar(60) NOT NULL, PRIMARY KEY (id));
create table yoroflow.org_auth_methods ( id uuid not null, auth_provider varchar(60) not null, allowed_domains varchar(500) not null, tenant_id varchar(60) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NULL, modified_on timestamp NULL, active_flag varchar(1) NOT NULL, primary key (id));

CREATE TABLE yoroflow.taskboard (id uuid NOT NULL,active_flag varchar(1) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,description varchar(100) NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,"name" varchar(100) NOT NULL,tenant_id varchar(60) NOT NULL,generated_task_id varchar(255) NULL,task_name varchar(255) NULL,taskboard_key varchar(255) NULL,is_column_background varchar(100) NULL,CONSTRAINT taskboard_pkey PRIMARY KEY (id));
CREATE TABLE yoroflow.taskboard_columns (id uuid NOT NULL,active_flag varchar(1) NOT NULL,column_color varchar(255) NOT NULL,column_name varchar(100) NOT NULL,column_order int8 NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,form_id varchar(100) NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,tenant_id varchar(60) NOT NULL,"version" int8 NOT NULL,taskboard_id uuid NOT NULL,layout_type varchar(255) NULL,is_column_background varchar(100) NULL,CONSTRAINT taskboard_columns_pkey PRIMARY KEY (id),CONSTRAINT fk3ib85k78h5k0hf7lhp7a2v36t FOREIGN KEY (taskboard_id) REFERENCES yoroflow.taskboard(id));
CREATE TABLE yoroflow.taskboard_columns_security (id uuid NOT NULL,taskboard_column_id uuid NOT NULL,group_id uuid NULL,user_id uuid NULL,"read" varchar(1) NOT NULL,"update" varchar(1) NOT NULL,"delete" varchar(1) NOT NULL,launch varchar(1) NOT NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,CONSTRAINT taskboard_columns_security_pkey PRIMARY KEY (id),CONSTRAINT fke1g9x7atjagstifalfjcvhltm FOREIGN KEY (taskboard_column_id) REFERENCES yoroflow.taskboard_columns(id));
CREATE TABLE yoroflow.taskboard_labels (id uuid NOT NULL,taskboard_id uuid NULL,label_name varchar(300) NULL,label_color varchar(100) NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,CONSTRAINT taskboard_labels_pkey PRIMARY KEY (id),CONSTRAINT fke1g9x7atjagstifalfjcvhltm FOREIGN KEY (taskboard_id) REFERENCES yoroflow.taskboard(id));
CREATE TABLE yoroflow.taskboard_security (id uuid NOT NULL,taskboard_id uuid NOT NULL,group_id uuid NULL,user_id uuid NULL,"read" varchar(1) NOT NULL,"update" varchar(1) NOT NULL,"delete" varchar(1) NOT NULL,launch varchar(1) NOT NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,CONSTRAINT taskboard_security_pkey PRIMARY KEY (id),CONSTRAINT fke1g9x7atjagstifalfjcvhltm FOREIGN KEY (taskboard_id) REFERENCES yoroflow.taskboard(id));
CREATE TABLE yoroflow.taskboard_task (id uuid NOT NULL,active_flag varchar(1) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,due_date timestamp NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,parent_task_id uuid NULL,start_date timestamp NULL,status varchar(100) NOT NULL,task_name varchar(255) NULL,task_type varchar(100) NOT NULL,tenant_id varchar(60) NOT NULL,taskboard_id uuid NOT NULL,task_data jsonb NULL,description varchar(255) NULL,task_id varchar(255) NULL,sequence_no int8 NULL,CONSTRAINT taskboard_task_pkey PRIMARY KEY (id),CONSTRAINT fkftylbh0b2ej2lrjm2tr1dlupn FOREIGN KEY (taskboard_id) REFERENCES yoroflow.taskboard(id));
CREATE TABLE yoroflow.taskboard_task_assigned_users (id uuid NOT NULL,active_flag varchar(1) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,group_id uuid NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,tenant_id varchar(60) NOT NULL,user_id uuid NULL,taskboard_task_id uuid NOT NULL,CONSTRAINT taskboard_task_assigned_users_pkey PRIMARY KEY (id),CONSTRAINT fk1eifumi2n3fw48gdy1qsylj91 FOREIGN KEY (taskboard_task_id) REFERENCES yoroflow.taskboard_task(id));
CREATE TABLE yoroflow.taskboard_task_comments (id uuid NOT NULL,active_flag varchar(1) NOT NULL,"comment" varchar(3000) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,reply_to_comment_id uuid NULL,tenant_id varchar(60) NOT NULL,taskboard_task_id uuid NOT NULL,CONSTRAINT taskboard_task_comments_pkey PRIMARY KEY (id),CONSTRAINT fk1s1dlxi7ntimw1u52wxfnkavm FOREIGN KEY (taskboard_task_id) REFERENCES yoroflow.taskboard_task(id));
CREATE TABLE yoroflow.taskboard_task_files (id uuid NOT NULL,taskboard_task_id uuid NOT NULL,file_type varchar(100) NULL,file_path varchar(100) NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,file_name varchar NULL,CONSTRAINT taskboard_task_files_pkey PRIMARY KEY (id),CONSTRAINT fke1g9x7atjagstifalfjcvhltm FOREIGN KEY (taskboard_task_id) REFERENCES yoroflow.taskboard_task(id));
CREATE TABLE yoroflow.taskboard_task_labels (id uuid NOT NULL,taskboard_task_id uuid NOT NULL,taskboard_labels_id uuid NOT NULL,label_name varchar(300) NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,CONSTRAINT taskboard_task_labels_pkey PRIMARY KEY (id),CONSTRAINT taskboard_labels_fkey FOREIGN KEY (taskboard_labels_id) REFERENCES yoroflow.taskboard_labels(id),CONSTRAINT taskboard_task_fkey FOREIGN KEY (taskboard_task_id) REFERENCES yoroflow.taskboard_task(id));

CREATE TABLE yoroflow.event_automation (id uuid NOT NULL,taskboard_id uuid NOT NULL,automation jsonb NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,rule_active varchar(1) NOT NULL,automation_type varchar(100) NULL,CONSTRAINT event_automation_pkey PRIMARY KEY (id),CONSTRAINT fke1g9x7atjagstifalfjcvhltm FOREIGN KEY (taskboard_id) REFERENCES yoroflow.taskboard(id));

CREATE TABLE yoroflow.taskboard_sub_status (id uuid NOT NULL,taskboard_column_id uuid not null,sub_status_name varchar(100) NOT NULL,sub_status_color varchar(100) NOT NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,CONSTRAINT taskboard_sub_status_pkey PRIMARY KEY (id),constraint taskboard_sub_status_fkey foreign key (taskboard_column_id) REFERENCES yoroflow.taskboard_columns(id));
CREATE TABLE yoroflow.org_auth_associate_group (associate_id uuid NOT NULL, id uuid NOT NULL, group_id uuid NOT NULL, tenant_id varchar(60) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NULL, modified_on timestamp NULL, active_flag varchar(1) NOT NULL, CONSTRAINT org_auth_associate_group_pk PRIMARY KEY (associate_id), CONSTRAINT org_auth_associate_group_org_auth_methods_fk FOREIGN KEY (id) REFERENCES yoroflow.org_auth_methods(id));

CREATE TABLE yoroflow.yoro_roles (role_id uuid NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL,	created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, role_desc varchar(250) NULL, role_name varchar(50) NOT NULL, tenant_id varchar(60) NOT NULL, managed_flag varchar(1) NOT NULL, role_color varchar(50) NULL, CONSTRAINT roles_pkey PRIMARY KEY (role_id));
CREATE TABLE yoroflow.user_associate_roles (user_associate_role_id uuid NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL,	modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, user_id uuid NOT NULL, role_id uuid NOT NULL, CONSTRAINT user_associate_roles_pkey PRIMARY KEY (user_associate_role_id),	CONSTRAINT fk97mxvrajhkq19dmvboprimeg1 FOREIGN KEY (role_id) REFERENCES yoroflow.yoro_roles(role_id), CONSTRAINT user_associate_roles_fk FOREIGN KEY (user_id) REFERENCES yoroflow.users(user_id));
CREATE TABLE yoroflow.org_auth_associate_roles (id uuid NOT NULL, org_auth_methods_id uuid NOT NULL, role_id uuid NOT NULL,	tenant_id varchar(60) NOT NULL,	created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NULL,	modified_on timestamp NULL,	active_flag varchar(1) NOT NULL, CONSTRAINT org_auth_associate_roles_pk PRIMARY KEY (id), CONSTRAINT org_auth_associate_roles_org_auth_methods_fk FOREIGN KEY (org_auth_methods_id) REFERENCES yoroflow.org_auth_methods(id));
CREATE TABLE yoroflow.menu_details_associate_roles (menu_details_associate_role_id uuid NOT NULL, menu_details_id uuid NOT NULL, role_id uuid NOT NULL,	active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NOT NULL, modified_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, menu_id uuid NULL, CONSTRAINT menu_details_associate_roles_pkey PRIMARY KEY (menu_details_associate_role_id), CONSTRAINT fk97mxvrajhkq19dmvboprimeg1 FOREIGN KEY (role_id) REFERENCES yoroflow.yoro_roles(role_id), CONSTRAINT menu_details_associate_roles_fk FOREIGN KEY (menu_details_id) REFERENCES yoroflow.menu_details(id));
CREATE TABLE yoroflow.payment_settings (uuid uuid NOT NULL,	ya_stripe_key_name varchar(100) NOT NULL, ya_description varchar(3000) NULL, ya_publish_key varchar(500) NOT NULL, ya_secret_key varchar(500) NOT NULL,	tenant_id varchar(60) NOT NULL,	created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, modified_by varchar(100) NULL,	modified_on timestamp NOT NULL,	active_flag varchar(1) NOT NULL, CONSTRAINT payment_settings_pkey PRIMARY KEY (uuid));

CREATE TABLE yoroflow.org_integrated_apps (id uuid NOT NULL,app_name varchar(100) NOT NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,auth_token varchar(1000) NULL, is_removed varchar(1) null, CONSTRAINT org_integrated_apps_pkey PRIMARY KEY (id));

CREATE TABLE yoroflow.auth_two_factor_methods (id uuid NOT NULL, method_name varchar(100) NOT NULL, active_flag varchar(1) NOT NULL, created_by varchar(100) NOT NULL, created_on timestamp NOT NULL, updated_by varchar(100) NOT NULL, updated_on timestamp NOT NULL, tenant_id varchar(60) NOT NULL, CONSTRAINT auth_two_factor_methods_pkey PRIMARY KEY (id));

CREATE TABLE yoroflow.taskboard_apps (id uuid NOT NULL,taskboard_id uuid NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,app_name varchar(100) NULL,CONSTRAINT taskboard_apps_pkey PRIMARY KEY (id),CONSTRAINT taskboard_foreign_key FOREIGN KEY (taskboard_id) REFERENCES yoroflow.taskboard(id));
CREATE TABLE yoroflow.taskboard_apps_config (id uuid NOT NULL,taskboard_id uuid NULL,taskboard_apps_id uuid null,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,auth_type varchar(100) NULL,auth_token varchar(1000) NULL,api_key varchar(100) NULL,api_secret varchar(1000) NULL,client_id varchar(100) NULL,client_secret varchar(1000) NULL,CONSTRAINT taskboard_apps_config_pkey PRIMARY KEY (id),CONSTRAINT taskboard_foreign_key FOREIGN KEY (taskboard_id) REFERENCES yoroflow.taskboard(id),CONSTRAINT taskboard_apps_key FOREIGN KEY (taskboard_apps_id) REFERENCES yoroflow.taskboard_apps(id));
CREATE TABLE yoroflow.org_integrated_apps_config (id uuid NOT NULL,org_integrated_apps_id uuid NULL,tenant_id varchar(60) NOT NULL,created_by varchar(100) NOT NULL,created_on timestamp NOT NULL,modified_by varchar(100) NULL,modified_on timestamp NOT NULL,active_flag varchar(1) NOT NULL,auth_type varchar(100) NULL,auth_token varchar(1000) NULL,api_key varchar(100) NULL,api_secret varchar(1000) NULL,client_id varchar(100) NULL,client_secret varchar(1000) NULL,CONSTRAINT org_integrated_apps_config_pkey PRIMARY KEY (id),CONSTRAINT org_integrated_apps_pkey FOREIGN KEY (org_integrated_apps_id) REFERENCES yoroflow.org_integrated_apps(id));


alter table if exists yoroflow.taskboard_sub_status add column_order int8 NULL;
alter table if exists yoroflow.taskboard_task add sub_status varchar(100) NULL;
alter table if exists yoroflow.taskboard_task add previous_status varchar(100) NULL;
alter table if exists yoroflow.grid_columns add CONSTRAINT fke1g9x7atjagstifalfjcvhltm FOREIGN KEY (grid_id) REFERENCES yoroflow.grids(grid_id)
alter table if exists yoroflow.users add CONSTRAINT uk_k8d0f2n7n88w1a16yhua64onx UNIQUE (user_name)
alter table if exists yoroflow.users add CONSTRAINT uk_pwrpg821nujmmnavoq7s420jn UNIQUE (email_id)
alter table if exists yoroflow.yoro_groups_user add CONSTRAINT fkauyseg6jagxf4mus8wcq3h59y FOREIGN KEY (group_id) REFERENCES yoroflow.yoro_groups(id)
alter table if exists yoroflow.yoro_groups_user add CONSTRAINT fksl2jutaberu1c3vapgsgeqi6h FOREIGN KEY (user_id) REFERENCES yoroflow.users(user_id)
alter table if exists yoroflow.page_permissions add CONSTRAINT fkb1aowyxbkve5xpeq806kckwmu FOREIGN KEY (page_id) REFERENCES yoroflow.page(id)
alter table if exists yoroflow.page_permissions add CONSTRAINT fkp6hm09wogk9r7tgamvu1cpxxq FOREIGN KEY (group_id) REFERENCES yoroflow.yoro_groups(id)
alter table if exists yoroflow.table_objects_columns add CONSTRAINT table_objects_columns_table_objects_id FOREIGN KEY (table_objects_id) REFERENCES yoroflow.table_objects(table_objects_id)
alter table if exists yoroflow.process_def_task_permission add CONSTRAINT fk35qnpgo1ae274aqxpfjxt70eb FOREIGN KEY (task_id) REFERENCES yoroflow.process_definition_tasks(task_id)
alter table if exists yoroflow.message_group_users add CONSTRAINT message_group_users_message_group_id_fkey FOREIGN KEY (message_group_id) REFERENCES yoroflow.message_group(id)
alter table if exists yoroflow.message_group_users add CONSTRAINT message_group_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES yoroflow.users(user_id)
alter table if exists yoroflow.menu add CONSTRAINT menu_application_id_fkey FOREIGN KEY (application_id) REFERENCES yoroflow.application(id)
alter table if exists yoroflow.menu_details add	CONSTRAINT menu_details_custom_page_id_fkey FOREIGN KEY (custom_page_id) REFERENCES yoroflow.custom_pages(id)
alter table if exists yoroflow.menu_details add	CONSTRAINT menu_details_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES yoroflow.menu(menu_id)
alter table if exists yoroflow.menu_details add	CONSTRAINT menu_details_page_id_fkey FOREIGN KEY (page_id) REFERENCES yoroflow.page(id)
alter table if exists yoroflow.application_permissions add CONSTRAINT application_permissions_application_id_fkey FOREIGN KEY (application_id) REFERENCES yoroflow.application(id)
alter table if exists yoroflow.application_permissions add CONSTRAINT application_permissions_group_id_fkey FOREIGN KEY (group_id) REFERENCES yoroflow.yoro_groups(id)
alter table if exists yoroflow.custom_page_permissions add CONSTRAINT fkb1aowyxbkve5xpeq806kckwmu FOREIGN KEY (custom_page_id) REFERENCES yoroflow.custom_pages(id)
alter table if exists yoroflow.custom_page_permissions add CONSTRAINT fkp6hm09wogk9r7tgamvu1cpxxq FOREIGN KEY (group_id) REFERENCES yoroflow.yoro_groups(id)
alter table if exists yoroflow.grid_filter add CONSTRAINT fkinmkg3j0hk32fm8vel8402o7a FOREIGN KEY (grid_id) REFERENCES yoroflow.grids(grid_id)
alter table if exists yoroflow.environment_variable add CONSTRAINT environment_variable_fkey FOREIGN KEY (process_definition_id) REFERENCES yoroflow.process_definitions(process_definition_id)
alter table if exists yoroflow.service_token add CONSTRAINT service_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES yoroflow.users(user_id)
alter table if exists yoroflow.user_permission add CONSTRAINT user_permission_service_token_id_fkey FOREIGN KEY (service_token_id) REFERENCES yoroflow.service_token(id)
alter table if exists yoroflow.user_custom_attribute add CONSTRAINT user_custom_attribute_user_id_fkey FOREIGN KEY (user_id) REFERENCES yoroflow.users(user_id)
alter table if exists yoroflow.workflow_report_permission add CONSTRAINT fkow4k4flgq9lumefll6244imyw FOREIGN KEY (report_id) REFERENCES yoroflow.workflow_report(report_id)
