package com.yorosis.taskboard.models;

public enum TaskType {
	USER_TASK, SEQ_FLOW, START_TASK, DECISION_TASK, EMAIL_TASK, END_TASK, APPROVAL_TASK, DB_TASK, DELAY_TIMER, COMPUTE_TASK, WEB_SERVICE_TASK,
	CALL_ANOTHER_WORKFLOW, DECISION_TABLE, SMS_TASK, COUNTER_TASK, EXCEL_REPORT;

}
