@Library("yorosis-shared-library") _

standardPipeline {
    projectType = "java-service"
    deploymentName = "taskboard-service-deployment"
    dockerImageName = "taskboard-service"
    canSkipSonarQubeCheck = true
    canBuildDockerImage = true
    canDeployImage = true
}